import Head from 'next/head'
import styles from '../styles/Home.module.css'
import HomePage from './home'

export default function Home() {
  return (
    <div>
    <div className={styles.container}>
      <Head>
        <title>ChainCode</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    </div>
    <HomePage />
    </div>

  )
}
